workflows:
  macos-release-build:
    name: macOS Release Build

    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      flutter: 3.41.6
      xcode: latest

    scripts:
      - name: Enable macOS
        script: flutter config --enable-macos-desktop

      - name: Get Packages
        script: flutter pub get

      - name: Build macOS App
        script: |
          flutter build macos --release

      - name: Package App
        script: |
          mkdir -p artifacts
          cp -R build/macos/Build/Products/Release/*.app artifacts/
          cd artifacts
          zip -r app-macos.zip *.app

    artifacts:
      - artifacts/*.zip
